### ISSUE TITLE
Automate HTTPS deploy

### ISSUE THREAD

**Issue by emmorais** [paulo308/bigseaAAAaaS#15]
Since we will implement AAA as a Service, it will be necessary to deploy new instances on demand. These instances must be configured over HTTPS. This task is responsible for the implementation of an automatic deploy of HTTPS instances.

**Comment by paulo308** [comment]
Done, partially. Is configured and works with an approach of central server, for the eubra.dei.uc.pt domain. Further experiments and development is needed on multiple instantiation and different domain names.

**Comment by paulo308** [comment]
Done. Now it is possible to introduce necessary parameters.
