### ISSUE TITLE
Implement authentication manager web interface

### ISSUE THREAD

**Issue by emmorais** [paulo308/bigseaAAAaaS#17]
It is necessary to have web pages to manage user information. Each application has an admin user that will be able to access this GUI in order to create, read, update and delete (CRUD) data from the system. A master admin will be the user that can manipulate data from any application.

**Comment by paulo308** [comment]
Additionally, there will be a GUI for each user to access (after login) and update their info. Ex: password or email.

**Comment by paulo308** [comment]
On it

**Comment by paulo308** [comment]
User's part is done. Admin part could be released in a future version (?) .
