### ISSUE TITLE
Add possibility of more than one email per user

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#27]
It is necessary to allow the user to have more than one email associated to its account. For this, we can setup a primary email, and secondary ones. With its it will be also possible to link accounts to external services through email (e.g. federation or external sign in's). 

Furthermore, additional email can be also handy for authorisation: for instance, users with emails from certain domains (e.g. "*@gmail.com" or "*@dei.uc.pt") can access specific applications, data or resources.

**Comment by emmorais** [comment]
On it.
