### ISSUE TITLE
Resend confirmation email (sign up process)

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#36]
Problems can occur. The user might not receive the confirmation email, or might have deleted it by mistake. It is necessary to create an endpoint that would allow the user to click an option like: " If you did not receive the confirmation email, please click here to issue a new one"

In this case, in a new page (or by REST API if not through our front end) the user would indicate the username or email address that he registered on the sign up process and a new confirmation email would be sent.

**Comment by emmorais** [comment]
On it
