### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#37]
If the user forget the password, there must be a mechanism to reset it. The user can indicate the username or email of the account, and if it exists, there are two possibilites:

- An email is sent with a randomly generated password;

- An email is sent with a temporary password and with a link to the "change data page". Here is where the introduces the temporary password as "old password" and defines a new password. This option however, might not be suitable for all use cases (e.g. Android app). 

Thereby, perhaps the first option would be more generalist and work for both cases. By letting the user keep the randomly generated password, or suggesting to change the password.

**Comment by emmorais** [comment]
On it.
