### ISSUE TITLE
Ask for email confirmation when adding a secondary email to account

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#38]
When the user registers a new email (different the main email that was introduced on the sign up process) he should confirm the operation. 

The confirmation can be made in two steps, like so:

- Sending a confirmation email to the main email of the account. 

- Sending a confirmation email to the email that is being registered.

After confirmation of the two links sent to the emails, the service confirms the identity of the user and ownership of the emails at the same time. After this point the secondary email is associated to the user account.

**Comment by emmorais** [comment]
On it.
