### ISSUE TITLE
Stay Sign-In option

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#40]
Place a flag on the authentication API (call it V1 to keep the current ones functional for the apps that are using it) that indicates if a users wants to stay signed in for a longer period. 

By default, the flag is false, meaning a 12h expire date for the token. 

If the flag is true, the token will have extended validity: 7 days (168 hours). 

After the expriration of the token, the user must Sign In.

**Comment by emmorais** [comment]
On it.
