### ISSUE TITLE
Creation of endpoint for infrastructure

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#48]
creation of specific endpoint for mesos credentials verification. 

https://eubrabigsea.dei.uc.pt/engine/api/checkin_data_infra

Request structure (like a normal sign in):
"user=XXXXXXX&pwd=XXXXXXXX"

Response structure:
{"error":"","success":true, "cancelled":false,"user_info":{"principal":"XXXXX", "secret":"XXXXXX"}}

Error response structure:
{"error":"Invalid username or password", "success":false,"cancelled":false,"user_info":null}

principal and secret to be added to authorisation details as: infrastructure credentials {}

**Comment by emmorais** [comment]
On it.
