### ISSUE TITLE
Read values from initialisation file 

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#49]
Load IP address and port of mongoDB from file. 
Certificates are generated according to those values.
Pyramid starts considering those values.

necessary to periodically check if values do not change. if they change, mesos-dns script needs to be called and values updated.

**Comment by paulo308** [comment]
File name:
 “config.txt”
Info to read inside file:
AUTH_DB_HOST IP: 0.0.0.0
AUTH_DB_HOST PORT: 55555

**Comment by emmorais** [comment]
On it.

**Comment by paulo308** [comment]
Done. Pyramid is reading port number and host from environment variables in repository https://github.com/paulo308/AAAaaS_Webapp, branch envVar
