### ISSUE TITLE
Define a max number of favorites

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#52]
By defining a maximum number of favorites for each user, it is necessary to create a new enpoint where the current number of favorites being used (or free slots) is reported. Is this way the app developer can make the request beforehand and present the information to the user, if needed.

The endpoint receives the user's username and token. The answer can be, for instance:
used favorites: X
free favorites: Y

Where X and Y are the number of used and free favorites, respectively.

**Comment by emmorais** [comment]
On it.
