### ISSUE TITLE
Create additional favorite endpoint (combined search)

### ISSUE THREAD

**Issue by paulo308** [paulo308/bigseaAAAaaS#54]
This endpoint allows the app developer to search for favorties in a combined fashion. Instead on retrieving a specific favorite or all of them (currently available), is would be possible to make a combined search such as:
Request: username + city_id + country_id

The answer would be a select with all that user's favorites with such a city_id and country_id.

This approach reduces the overhead in communications, making it faster, lighter and more specific.

**Comment by emmorais** [comment]
On it.
